config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'trails#index'
  resources :trails
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/trail.rb
class Trail < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/trails_controller.rb
class TrailsController < ApplicationController
  def index
    @trails = Trail.order('updated_at DESC')
  end

  def new
    @trail = Trail.new
  end

  def create
    Trail.create(trail_params)
    redirect_to root_path
  end

  private
  
  def trail_params
    params.require(:trail).permit(:name, :location, :length, :elevation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/trails_helper.rb
module TrailsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Washington Trails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <link href="https://fonts.googleapis.com/css?family=Roboto+Slab:700|Roboto:400,400i,700" rel="stylesheet">
  </head>

  <body>
    <div class="top-bar">
      <div class="container">
        <div class="top-bar-left">
          <ul class="menu">
            <li class="menu logo"><%= link_to 'Washington Trails', root_path %></li>
          </ul>
        </div>
        <div class="top-bar-right">
          <ul class="menu">
            <li><%= link_to 'Add a Trail', new_trail_path, class: 'nav-link' %></li>
          </ul>
        </div>
      </div>
    </div>
    <br />
    <%= yield %>

  </body>
</html>

app/views/trails/index.html.erb
<div class="row align-center">
  <div class="columns small-11 large-6">
    <% @trails.each do |trail| %>
    <div class="row">
      <div class="card columns small-12">
        <h2><%= trail.name %></h2>
        <p><%= fa_icon "map-marker" %>&nbsp;<strong>Location:</strong> <%= trail.location %></p>
        <p><%= fa_icon "arrows-h" %>&nbsp;<strong>Length:</strong> <%= trail.length.to_f %> miles</p>
        <p><%= fa_icon "line-chart" %>&nbsp;<strong>Elevation:</strong> <%= trail.elevation %> ft</p>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/trails/new.html.erb
<div class="row align-center">
  <div class="columns small-11 large-6 card">
    <h2>Add a New Trail</h2>
    <%= simple_form_for @trail do |f| %>
      <%= f.input :name %>
      <%= f.input :location %>
      <%= f.input :length %>
      <%= f.input :elevation %>
      <%= f.submit 'Create New Trail', class: 'button' %>
    <% end %>
  </div>
</div>